### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by olivatooo** [antoniocavalcante/hdbscan-java#2]
After executing `compile.sh` I got the following error:

After executing `compile.sh` I got the following error:

./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:18: error: package it.unimi.dsi.fastutil does not exist
import it.unimi.dsi.fastutil.BigList;
                            ^
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:19: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
                                 ^
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:20: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntBigArrayBigList;
                                 ^
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:21: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntOpenHashSet;
                                 ^
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:26: error: cannot find symbol
	public Int2ObjectOpenHashMap<DistanceLevel>[] ExtendedRNG;
	       ^
  symbol:   class Int2ObjectOpenHashMap
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:28: error: cannot find symbol
	public IntBigArrayBigList[] RNG;
	       ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/util/FairSplitTree.java:4: error: package it.unimi.dsi.fastutil does not exist
import it.unimi.dsi.fastutil.BigList;
                            ^
./src/ca/ualberta/cs/util/FairSplitTree.java:5: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntBigArrayBigList;
                                 ^
./src/ca/ualberta/cs/util/FairSplitTree.java:6: error: package it.unimi.dsi.fastutil.longs does not exist
import it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap;
                                  ^
./src/ca/ualberta/cs/util/FairSplitTree.java:12: error: cannot find symbol
	public static Long2ObjectOpenHashMap<FairSplitTree> root;
	              ^
  symbol:   class Long2ObjectOpenHashMap
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:31: error: cannot find symbol
	public BigList<Integer> P;
	       ^
  symbol:   class BigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:67: error: cannot find symbol
	public FairSplitTree(FairSplitTree parent, BigList<Integer> P, double maxCD, int level, long id, int k, double[][] coreDistances){
	                                           ^
  symbol:   class BigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:187: error: cannot find symbol
	public BigList<Integer> retrieve() {		
	       ^
  symbol:   class BigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:251: error: cannot find symbol
	public static BigList<Integer> rangeSearch(FairSplitTree root, double[] queryPoint, double r, BigList<Integer> arrayList) {
	                                                                                              ^
  symbol:   class BigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:251: error: cannot find symbol
	public static BigList<Integer> rangeSearch(FairSplitTree root, double[] queryPoint, double r, BigList<Integer> arrayList) {
	              ^
  symbol:   class BigList
  location: class FairSplitTree
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:14: error: package it.unimi.dsi.fastutil.doubles does not exist
import it.unimi.dsi.fastutil.doubles.DoubleBigArrayBigList;
                                    ^
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:15: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntBigArrayBigList;
                                 ^
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:16: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntOpenHashBigSet;
                                 ^
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:32: error: cannot find symbol
	protected DoubleBigArrayBigList densities;
	          ^
  symbol:   class DoubleBigArrayBigList
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:10: error: package it.unimi.dsi.fastutil.doubles does not exist
import it.unimi.dsi.fastutil.doubles.DoubleBigArrayBigList;
                                    ^
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:11: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntBigArrayBigList;
                                 ^
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:53: error: cannot find symbol
	private IntBigArrayBigList level;
	        ^
  symbol:   class IntBigArrayBigList
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:144: error: cannot find symbol
	public DoubleBigArrayBigList getDensities() {
	       ^
  symbol:   class DoubleBigArrayBigList
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:331: error: cannot find symbol
	public IntBigArrayBigList toFileDynamic(int[] labels, double d, BufferedWriter hierarchyWriter) throws IOException {
	       ^
  symbol:   class IntBigArrayBigList
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:21: error: cannot find symbol
	private DoubleBigArrayBigList densityLevels;
	        ^
  symbol:   class DoubleBigArrayBigList
  location: class ObjInstance
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:22: error: cannot find symbol
	private IntBigArrayBigList clusterID;
	        ^
  symbol:   class IntBigArrayBigList
  location: class ObjInstance
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:89: error: cannot find symbol
	public IntBigArrayBigList getClusterID() {
	       ^
  symbol:   class IntBigArrayBigList
  location: class ObjInstance
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:93: error: cannot find symbol
	public void setClusterID(IntBigArrayBigList clusterID) {
	                         ^
  symbol:   class IntBigArrayBigList
  location: class ObjInstance
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:97: error: cannot find symbol
	public DoubleBigArrayBigList getDensities() {
	       ^
  symbol:   class DoubleBigArrayBigList
  location: class ObjInstance
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:7: error: package com.google.common.io does not exist
import com.google.common.io.Files;
                           ^
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:8: error: package com.google.gson does not exist
import com.google.gson.Gson;
                      ^
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:9: error: package com.google.gson does not exist
import com.google.gson.GsonBuilder;
                      ^
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:10: error: package com.google.gson does not exist
import com.google.gson.JsonObject;
                      ^
./src/ca/ualberta/cs/hdbscanstar/HDBSCANStar.java:25: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntAVLTreeSet;
                                 ^
./src/ca/ualberta/cs/hdbscanstar/HDBSCANStar.java:26: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntOpenHashBigSet;
                                 ^
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:9: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntAVLTreeSet;
                                 ^
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:10: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntOpenHashBigSet;
                                 ^
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:12: error: package org.apache.commons.math3.special does not exist
import org.apache.commons.math3.special.Gamma;
                                       ^
./src/ca/ualberta/cs/hdbscanstar/HDBSCANStar.java:1034: error: cannot find symbol
	private static Cluster createNewCluster(IntOpenHashBigSet points, int[] clusterLabels, Cluster parentCluster, int clusterLabel, double edgeWeight) {
	                                        ^
  symbol:   class IntOpenHashBigSet
  location: class HDBSCANStar
./src/ca/ualberta/cs/hdbscanstar/HDBSCANStar.java:1061: error: cannot find symbol
	private static void calculateNumConstraintsSatisfied(IntAVLTreeSet newClusterLabels, 
	                                                     ^
  symbol:   class IntAVLTreeSet
  location: class HDBSCANStar
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:38: error: cannot find symbol
	private IntAVLTreeSet virtualChildCluster;
	        ^
  symbol:   class IntAVLTreeSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:40: error: cannot find symbol
	private TreeMap<Integer, IntAVLTreeSet> preLabeledObjectsInNode;
	                         ^
  symbol:   class IntAVLTreeSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:59: error: cannot find symbol
	private IntOpenHashBigSet objectsAtBirthLevel;
	        ^
  symbol:   class IntOpenHashBigSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:60: error: cannot find symbol
	private IntAVLTreeSet children;
	        ^
  symbol:   class IntAVLTreeSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:63: error: cannot find symbol
	private IntOpenHashBigSet objects; //Objects that belong to this cluster i.e. become noise before/at the death level of this cluster.
	        ^
  symbol:   class IntOpenHashBigSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:77: error: cannot find symbol
	public Cluster(int label, Cluster parent, double birthLevel, long numPoints, IntOpenHashBigSet pointsAtBirthLevel) {
	                                                                             ^
  symbol:   class IntOpenHashBigSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:429: error: cannot find symbol
	public void addPointsToVirtualChildCluster(IntOpenHashBigSet points) {
	                                           ^
  symbol:   class IntOpenHashBigSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:585: error: cannot find symbol
	public IntAVLTreeSet getChildren() {
	       ^
  symbol:   class IntAVLTreeSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:589: error: cannot find symbol
	public IntOpenHashBigSet getObjectsAtBirthLevel() {
	       ^
  symbol:   class IntOpenHashBigSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:593: error: cannot find symbol
	public IntOpenHashBigSet getObjects() {
	       ^
  symbol:   class IntOpenHashBigSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:597: error: cannot find symbol
	public void setObjects(IntOpenHashBigSet objects) {
	                       ^
  symbol:   class IntOpenHashBigSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/Cluster.java:601: error: cannot find symbol
	public TreeMap<Integer, IntAVLTreeSet> getClassInformation() {
	                        ^
  symbol:   class IntAVLTreeSet
  location: class Cluster
./src/ca/ualberta/cs/hdbscanstar/HDBSCANStarRunner.java:12: error: package com.esotericsoftware.kryo does not exist
import com.esotericsoftware.kryo.Kryo;
                                ^
./src/ca/ualberta/cs/hdbscanstar/HDBSCANStarRunner.java:13: error: package com.esotericsoftware.kryo.io does not exist
import com.esotericsoftware.kryo.io.Output;
                                   ^
./src/ca/ualberta/cs/util/SparseDataset.java:7: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.Int2DoubleLinkedOpenHashMap;
                                 ^
./src/ca/ualberta/cs/util/SparseDataset.java:8: error: package it.unimi.dsi.fastutil.ints does not exist
import it.unimi.dsi.fastutil.ints.IntLinkedOpenHashSet;
                                 ^
./src/ca/ualberta/cs/util/SparseDataset.java:124: error: cannot find symbol
		public Int2DoubleLinkedOpenHashMap[] m;
		       ^
  symbol:   class Int2DoubleLinkedOpenHashMap
  location: class SparseDataset.SparseMatrix
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:64: error: cannot find symbol
		RNG = new IntBigArrayBigList[dataSet.length()];
		          ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:67: error: cannot find symbol
			RNG[i] = new IntBigArrayBigList();
			             ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:114: error: cannot find symbol
			ExtendedRNG = new Int2ObjectOpenHashMap[HDBSCANStarRunner.environment.dataset.length()];
			                  ^
  symbol:   class Int2ObjectOpenHashMap
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:117: error: cannot find symbol
				ExtendedRNG[i] = new Int2ObjectOpenHashMap<DistanceLevel>();
				                     ^
  symbol:   class Int2ObjectOpenHashMap
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:126: error: cannot find symbol
			RNG = new IntBigArrayBigList[HDBSCANStarRunner.environment.dataset.length()];
			          ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:129: error: cannot find symbol
				RNG[i] = new IntBigArrayBigList();
				             ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:354: error: cannot find symbol
		BigList<Integer> tempA = null;
		^
  symbol:   class BigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:355: error: cannot find symbol
		BigList<Integer> tempB = null;
		^
  symbol:   class BigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:385: error: cannot find symbol
					tempA = new IntBigArrayBigList();
					            ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:386: error: cannot find symbol
					tempB = new IntBigArrayBigList();
					            ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:404: error: cannot find symbol
		IntOpenHashSet B = new IntOpenHashSet((int)T2.getCount());
		^
  symbol:   class IntOpenHashSet
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:404: error: cannot find symbol
		IntOpenHashSet B = new IntOpenHashSet((int)T2.getCount());
		                       ^
  symbol:   class IntOpenHashSet
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:413: error: cannot find symbol
					tempA = new IntBigArrayBigList();
					            ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:414: error: cannot find symbol
					tempB = new IntBigArrayBigList();
					            ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:439: error: cannot find symbol
					tempA = new IntBigArrayBigList();
					            ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:440: error: cannot find symbol
					tempB = new IntBigArrayBigList();
					            ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:580: error: cannot find symbol
		BigList<Integer> result = FairSplitTree.rangeSearch(FairSplitTree.root.get(1), q, r, new IntBigArrayBigList());
		^
  symbol:   class BigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/hdbscanstar/RelativeNeighborhoodGraph.java:580: error: cannot find symbol
		BigList<Integer> result = FairSplitTree.rangeSearch(FairSplitTree.root.get(1), q, r, new IntBigArrayBigList());
		                                                                                         ^
  symbol:   class IntBigArrayBigList
  location: class RelativeNeighborhoodGraph
./src/ca/ualberta/cs/util/FairSplitTree.java:42: error: cannot find symbol
		FairSplitTree.root = new Long2ObjectOpenHashMap<FairSplitTree>();
		                         ^
  symbol:   class Long2ObjectOpenHashMap
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:46: error: cannot find symbol
		BigList<Integer> P = new IntBigArrayBigList();
		^
  symbol:   class BigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:46: error: cannot find symbol
		BigList<Integer> P = new IntBigArrayBigList();
		                         ^
  symbol:   class IntBigArrayBigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:149: error: cannot find symbol
				BigList<Integer> right = new IntBigArrayBigList();
				^
  symbol:   class BigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:149: error: cannot find symbol
				BigList<Integer> right = new IntBigArrayBigList();
				                             ^
  symbol:   class IntBigArrayBigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:150: error: cannot find symbol
				BigList<Integer> left  = new IntBigArrayBigList();
				^
  symbol:   class BigList
  location: class FairSplitTree
./src/ca/ualberta/cs/util/FairSplitTree.java:150: error: cannot find symbol
				BigList<Integer> left  = new IntBigArrayBigList();
				                             ^
  symbol:   class IntBigArrayBigList
  location: class FairSplitTree
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:72: error: cannot find symbol
		this.densities = new DoubleBigArrayBigList();
		                     ^
  symbol:   class DoubleBigArrayBigList
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:84: error: cannot find symbol
		this.level = new IntBigArrayBigList();
		                 ^
  symbol:   class IntBigArrayBigList
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:333: error: cannot find symbol
		IntBigArrayBigList level = new IntBigArrayBigList();
		^
  symbol:   class IntBigArrayBigList
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:333: error: cannot find symbol
		IntBigArrayBigList level = new IntBigArrayBigList();
		                               ^
  symbol:   class IntBigArrayBigList
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:420: error: cannot find symbol
		IntOpenHashBigSet writtenClusters = new IntOpenHashBigSet();
		^
  symbol:   class IntOpenHashBigSet
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/HMatrix.java:420: error: cannot find symbol
		IntOpenHashBigSet writtenClusters = new IntOpenHashBigSet();
		                                        ^
  symbol:   class IntOpenHashBigSet
  location: class HMatrix
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:36: error: cannot find symbol
		this.densityLevels = new DoubleBigArrayBigList();
		                         ^
  symbol:   class DoubleBigArrayBigList
  location: class ObjInstance
./src/ca/ualberta/cs/SHM/HMatrix/ObjInstance.java:37: error: cannot find symbol
		this.clusterID = new IntBigArrayBigList();
		                     ^
  symbol:   class IntBigArrayBigList
  location: class ObjInstance
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:57: error: cannot find symbol
		Gson gson = new GsonBuilder().setPrettyPrinting().create();
		^
  symbol:   class Gson
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:57: error: cannot find symbol
		Gson gson = new GsonBuilder().setPrettyPrinting().create();
		                ^
  symbol:   class GsonBuilder
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:61: error: cannot find symbol
		JsonObject progress = new JsonObject();
		^
  symbol:   class JsonObject
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:61: error: cannot find symbol
		JsonObject progress = new JsonObject();
		                          ^
  symbol:   class JsonObject
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:65: error: cannot find symbol
		JsonObject state = new JsonObject();
		^
  symbol:   class JsonObject
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:65: error: cannot find symbol
		JsonObject state = new JsonObject();
		                       ^
  symbol:   class JsonObject
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:72: error: cannot find symbol
		Files.write(json.getBytes(), path.toFile());
		^
  symbol:   variable Files
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:91: error: cannot find symbol
		Files.write(json.getBytes(), path.toFile());
		^
  symbol:   variable Files
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:124: error: cannot find symbol
		Files.write(json.getBytes(), path.toFile());
		^
  symbol:   variable Files
  location: class ExperimentIHDBSCANStar
./src/ca/ualberta/cs/experiments/ExperimentIHDBSCANStar.java:143: error: cannot find symbol
			Files.write(json.getBytes(), path.toFile());
			^
  symbol:   variable Files
  location: class ExperimentIHDBSCANStar
100 errors

**Comment by antoniocavalcante** [comment]
It looks like you don't have the fastutil dependency. Try running maven before running this script. I should also let you know that while this script is handful to automate stuff, I have noticed in the past a performance difference between the jar generated by this script and the one exported by Eclipse (the jar exported by Eclipse was usually faster).

**Comment by olivatooo** [comment]
running `mvn install` worked for me!
