### ISSUE TITLE
Question about HAI

### ISSUE THREAD

**Issue by olivatooo** [antoniocavalcante/hdbscan-java#3]
This HAI.java implementation is compatible with the hierarchy generated by the python version of hdbscan?

I'm trying to use it with the single linkage tree generated by the python implementation of hdbscan but without success. 😢 

I didn't found any other HAI implementation besides this in java and the cython version in mustache repository.

**Comment by antoniocavalcante** [comment]
Hi Gabriel, unfortunately I'm afraid this java version is not compatible with the output generated by the Python version of HDBSCAN*. If you're interested, there is also a Matlab version made available by the authors (https://web.eecs.umich.edu/~jjcorso/#codeanddata) but I'm not sure if it's compatible with the single linkage tree format from python.

**Comment by olivatooo** [comment]
Thanks ❤️  I'll look towards the matlab version!
